spring.application.name=rubium-website


spring.data.mongodb.uri=mongodb+srv://sharmavn258_db_user:vanshsh12@cluster0.crl7ag1.mongodb.net/rubium?retryWrites=true&w=majority
spring.data.mongodb.database=rubium

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hello.rubiumai@gmail.com
spring.mail.password=zsbaxelsosjxomkb

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true