#rubium341-?atlas pass

spring.application.name=rubium-website
spring.data.mongodb.database=rubium

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=openai/gpt-4o-mini



spring.data.mongodb.uri=${MONGODB_URI}

spring.resend.api-key=${RESEND_API_KEY}

#server.port=${PORT:8080}


